language: node_js
node_js: 
-10.13.0

cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  bucket: elasticbeanstalk-us-east-2-337419897283
  region: us-east-2

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: elasticbeanstalk-us-east-2-337419897283
  key: latest.zip
  bundle_type: zip
  application: hello-koa
  deployment_group: group1-ec2
  region: us-east-2

script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip